### ISSUE TITLE
GH60 firmware cannot compile . it was a bus or just slip of the pen ?

### ISSUE THREAD

**Issue by Sasasu** [kairyu/tmk_keyboard_custom#7]
https://github.com/Sasasu/tmk_keyboard_custom/commit/a75d8545d1b76389fd6b462bca62cfc2a6b221e2

**Comment by kairyu** [comment]
Did you mean "typo"?

It was not a typo. The code in gh60 folder was merely not up-to-date. Please refer to 08d721de8ad7f5dfba78afdae08447d959bd6d02.
